django_lect/urls.py
from django.contrib import admin
from django.urls import path, include

from django_lect import views
# 로컬에서 서버를 실행시키면 기본 도메인이 127.0.0.1:8000 이 되고,
# 서버에 배포를 하면 해당 ip 혹은 설정한 도메인(www.naver.com)이 기본 도메인이 된다.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homeview, name='home'),
    path('mgr/', include('mgr.urls')),
    path('app/', include('service.urls')),
]
# 127.0.0.1/8000/mgr/ => 관리자 홈
# 127.0.0.1/8000/mgr/signup

mgr/urls.py
from django.urls import path

from mgr import views

app_name = 'mgr'
urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='sign_up'),
]

service/urls.py
from django.urls import path
from service import views
from service._requests import _ajax

app_name = 'service'
urlpatterns = [
    path('member/list', views.account_list_view, name='account_list'),
    path('ajax/member/list', _ajax.account_list, name='ajax_account_list'),
]

mgr/models.py
from django.db import models

# Create your models here.
class DLAccount(models.Model):
    name = models.CharField(max_length=20, null=False, blank=False, default='')
    address = models.TextField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    nickName = models.CharField(max_length=20, null=True, blank=True)
    profileImg = models.ImageField(null=True, blank=True)
    user = models.OneToOneField('auth.User', blank=False, null=False, related_name='user_account', default='0',
                                on_delete=models.CASCADE)
    class Meta:
        db_table = 'mgr_account'

service/models.py
from django.db import models

# Create your models here.
class DLBoard(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, default='')
    content = models.TextField(null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)
    createdDate = models.DateTimeField(auto_now_add=True)
    modifiedDate = models.DateTimeField(auto_now=True)
    mainImg = models.ImageField(null=True, blank=True)
    account = models.ForeignKey('mgr.DLAccount', blank=True, null=True, related_name='account_board', default='0',
                                on_delete=models.SET_NULL)
    class Meta:
        db_table = 'service_board'

mgr/forms.py
from django import forms

from mgr.models import DLAccount


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='패스워드 입력')
    class Meta:
        model = DLAccount
        fields = ['name', 'password', 'address', 'age', 'nickName', 'profileImg']
        labels ={
            'name':'이름'
        }

django_lect/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView


def homeview(requeset):
    context = {'intro': '안녕하세요.'}
    return render(requeset, 'home.html', context=context)

mgr/views.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import FormView

from mgr.forms import SignUpForm


class SignUpView(FormView):
    template_name = 'mgr/sign_up.html'
    form_class = SignUpForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        myform = form.save(commit=False)
        # 회원 가입이기 때문에 django 기본 유저를 새로 생성하는 부분.
        user = User()
        user.username = myform.name
        user.password = make_password(form.cleaned_data['password'])
        user.save()
        # 저장한 유저를 account 모델에 저장.
        myform.user = user
        myform.save()
        form.save_m2m()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        context = super().get_context_data()
        context['info'] = "회원가입페이지 입니다."
        return self.render_to_response(context)





# template 를 호출 할때, class view 및 function view 가 있음.
# class view 는 django의 여러가지 (ex. FormView) 를 상속받는데, 이 다양한 views 들은 특정 목적에서 조금 편하게 할 수 있도록
# 상속을 거쳐서 구조화 되어 잇음.

# function view 는 request에 대한 모든 작업을 다 해줘야하는 (get, post 별로 다 각각 직접처리해야함) views(장고의 템플릿 return 부)

service/views.py
import json

from django.core import serializers
from django.forms import model_to_dict
from django.shortcuts import render

# Create your views here.
from mgr.models import DLAccount


def account_list_view(request):
    context = {}

    return render(request, 'service/account_list.html', context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>


      <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>

<body>
<div class="bs-component">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mgr:sign_up' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'service:account_list' %}">회원리스트</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</div>
    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->



        <!-- Main -->
        <div id="main">
            {% block main %}

            {% endblock %}
        </div>

        <!-- Footer -->
        <footer id="footer">

        </footer>

    </div>

    <!-- Scripts -->


</body>
</html>

templates/home.html
{% extends 'base.html' %}

   {% block main %}
   {{ intro }}
   {% endblock %}

templates/mgr/sign_up.html
{% extends 'base.html' %}

{% block main %}
    <h2>{{ info }}</h2>
    <form method="post" action="{% url 'mgr:sign_up' %}">
    {% csrf_token %}
        {{ form.as_p }}
    <button class="btn btn-primary">저장</button>
    </form>
{% endblock %}

templates/service/account_list.html
{% extends 'base.html' %}

{% block main %}
    {% load static %}
    <script src="{% static 'js/service.js' %}"></script>
    <style>
     div#account-list span
     {
         margin: 1rem;
     }
     div#account-list div
     {
         display: flex;
     }
    </style>

    {% csrf_token %}
<div id="account-list">

</div>
    <script>

        $(document).ready(function () {
            url = '{% url 'service:ajax_account_list' %}';
            make_account_list(function (data)
            {
                let html='';
                data.result.forEach(function (ele)
                {
                    accountInfo.accList.push({'obj_id':ele.id ,'name':ele.name, 'nickName':ele.nickName,
                    'address':ele.address, 'age':'ele.age'});
                    html += `<div><span>${ele.name}</span><span>${ele.nickName}</span><span>${ele.address}</span>
                    <span>${ele.age}</span></div>`;

                })
                $("#account-list").append(html);
                console.log(accountInfo);
            });
        });


    </script>
{% endblock %}